### PR TITLE
web: add ssh keys for pulp_installer, pulp_operator

### PR DESCRIPTION
**Pull request by dkliban**

### CODE REVIEW

**Review by fao89 — APPROVED** [review]
Thank you!

**Comment by dkliban** [comment]
@duck-rh and @mscherer do you understand the ansible lint failures here?

**Comment by duck-rh** [comment]
@dkliban yes, the linting tool found some problems. It sometimes add new checks and become stricter, so we need to adapt some rules. Let me address this in another PR.

**Comment by duck-rh** [comment]
@dkliban I made changes in #20 and #21 , could you rebase your work on top of it please?

**Pull request merged**
