### PR TITLE
Remove fixtures, as it is nolonger hosted on that server

### PR DESCRIPTION
**Pull request by mscherer**

### CODE REVIEW

**Comment by mscherer** [comment]
@duck-rh Can you take a look when you are back ? I am not admin, so I can't merge that, and I am not sure why it still requests the old 3.6 build.

**Review by ggainey — CHANGES_REQUESTED** [review]
We still very much need fixtures.pulpproject.org - if this would remove it, I'm opposed :)

**Comment by mscherer** [comment]
Sorry, your license has expired, I have to remove it :p 

More seriously, fixtures is now running on our openshift cluster, so the old deployment on the VM (www) is what this one remove (and it just remove the deployment part, because I think the server part have been cleaned and break since the DNS is no longer pointing to that server)

**Comment by ggainey** [comment]
> Sorry, your license has expired, I have to remove it :p

:)


> More seriously, fixtures is now running on our openshift cluster, so the old deployment on the VM (www) is what this one remove (and it just remove the deployment part, because I think the server part have been cleaned and break since the DNS is no longer pointing to that server)

Ah!  Perfect, I am Unconfused now, thanks!

**Review by ggainey — APPROVED** [review]

**Pull request merged**
